# Generated by Django 3.2.12 on 2023-03-28 05:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('profile_type', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], max_length=30)),
                ('area_of_interest', models.CharField(max_length=100)),
                ('school', models.CharField(choices=[('SBS', 'SBS'), ('SCS', 'SCS'), ('SPS', 'SPS'), ('SMSS', 'SMSS'), ('SHSS', 'SHSS'), ('SCEE', 'SCEE'), ('SMMS', 'SMMS'), ('SCENE', 'SCENE'), ('SoM', 'SoM')], max_length=100)),
                ('rollno', models.CharField(max_length=10)),
                ('year', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], max_length=30)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('DSE', 'DSE'), ('ME', 'ME'), ('EE', 'EE'), ('CE', 'CE'), ('BioE', 'BioE'), ('EP', 'EP')], max_length=30)),
                ('cv', models.FileField(upload_to='resumes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('linked_in_link', models.CharField(blank=True, max_length=100)),
                ('portfolio_link', models.CharField(blank=True, max_length=100)),
                ('github_link', models.CharField(blank=True, max_length=100)),
                ('liked_projects', models.ManyToManyField(blank=True, related_name='liked_projects', to='home.Project')),
                ('starred_projects', models.ManyToManyField(blank=True, related_name='starred_projects', to='home.Project')),
                ('techskills', models.ManyToManyField(related_name='techskills', to='home.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=30)),
                ('notification_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_creater', to=settings.AUTH_USER_MODEL)),
                ('project_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_requested', to='home.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
