# Generated by Django 4.0 on 2021-12-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('DSE', 'DSE'), ('ME', 'ME'), ('EE', 'EE'), ('CE', 'CE'), ('BioE', 'BioE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], max_length=30),
        ),
    ]
