# Generated by Django 3.2.5 on 2021-12-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(default='/', max_length=30),
            preserve_default=False,
        ),
    ]
