# Generated by Django 4.0.1 on 2022-01-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_liked_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_link',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='linked_in_link',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_link',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
    ]
