# Generated by Django 4.0 on 2022-03-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_applyrequest_project'),
        ('users', '0013_alter_profile_github_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='techskills',
        ),
        migrations.AddField(
            model_name='profile',
            name='techskills',
            field=models.ManyToManyField(related_name='techskills', to='home.Tag'),
        ),
    ]
