# Generated by Django 4.0 on 2021-12-25 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Status', models.CharField(choices=[('Open', 'Open'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Open', max_length=10)),
                ('Difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard')], default='Beginner', max_length=15)),
                ('PreRequisite', models.TextField()),
                ('Duration', models.CharField(max_length=30)),
                ('DatePosted', models.DateTimeField(default=django.utils.timezone.now)),
                ('SelectionCriteria', models.TextField()),
                ('OpenedFor', models.TextField()),
                ('AlreadyApplied', models.ManyToManyField(blank=True, related_name='AlreadyApplied', to=settings.AUTH_USER_MODEL)),
                ('ApplyRequest', models.ManyToManyField(blank=True, related_name='ApplyRequest', to=settings.AUTH_USER_MODEL)),
                ('FloatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('Mentors', models.ManyToManyField(blank=True, related_name='Mentors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
