# Generated by Django 4.0 on 2021-12-21 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('FloatedBy', models.CharField(max_length=30)),
                ('Mentors', models.TextField()),
                ('Status', models.CharField(choices=[('1', 'Open'), ('2', 'Ongoing'), ('3', 'Completed')], default='Open', max_length=1)),
                ('Difficulty', models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Hard')], default='Beginner', max_length=1)),
                ('PreRequisite', models.TextField()),
                ('Duration', models.DurationField()),
                ('DatePosted', models.DateTimeField(default=django.utils.timezone.now)),
                ('SelectionCriteria', models.TextField()),
                ('OpenedFor', models.TextField()),
                ('AlreadyApplied', models.TextField()),
            ],
        ),
    ]
