# Generated by Django 3.2.18 on 2023-03-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='PreRequisite',
            new_name='DesiredQualifications',
        ),
    ]
