# Generated by Django 4.0 on 2021-12-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard')], default='Beginner', max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='Status',
            field=models.CharField(choices=[('Open', 'Open'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Open', max_length=10),
        ),
    ]
