# Generated by Django 4.1.7 on 2023-03-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_prerequisite_project_desiredqualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Question',
            field=models.TextField(blank=True),
        ),
    ]
