# Generated by Django 3.2.5 on 2021-12-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_project_openedfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='OpenedFor',
            field=models.CharField(max_length=300),
        ),
    ]
