# Generated by Django 4.1.7 on 2023-03-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_project_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Question',
            field=models.TextField(),
        ),
    ]
