# Generated by Django 3.2.5 on 2021-12-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_project_openedfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='MailNotification',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
