# Generated by Django 4.0.1 on 2022-01-09 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_remove_project_mentors_project_mentors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Mentors',
            field=models.ManyToManyField(related_name='Mentors', to=settings.AUTH_USER_MODEL),
        ),
    ]
