# Generated by Django 4.0 on 2022-01-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_project_mentors'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
    ]
