# Generated by Django 4.0 on 2022-01-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_project_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Tags',
            field=models.ManyToManyField(related_name='Tags', to='home.Tags'),
        ),
    ]
