# Generated by Django 4.0 on 2022-01-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_tags_project_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
