# Generated by Django 4.0 on 2022-01-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Duration',
            field=models.CharField(choices=[('Less Than', (('1', '< 1 months'), ('2', '< 2 months'), ('4', '< 4 months'), ('<6', '< 6 months'))), ('More Than', (('>6', '> 6 months'), ('12', '> 12 months')))], max_length=30),
        ),
    ]
