# Generated by Django 4.0 on 2022-02-17 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0015_alter_project_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ApplyRequest',
        ),
        migrations.CreateModel(
            name='ApplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=10)),
                ('Project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
