# Generated by Django 4.0 on 2022-03-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_applyrequest_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Image',
            field=models.ImageField(blank=True, default='images.jpeg', upload_to='project_pics'),
        ),
        migrations.AddField(
            model_name='project',
            name='Question',
            field=models.TextField(default='Temporary question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='Duration',
            field=models.CharField(choices=[('1', '< 1 month'), ('1-2', '1-2 months'), ('2-4', '2-4 months'), ('4-6', '4-6 months'), ('6-12', '6-12 months'), ('12', '> 12 months')], max_length=30),
        ),
    ]
