# Generated by Django 4.0 on 2022-03-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_project_image_project_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='MailNotification',
        ),
    ]
