# Generated by Django 4.0 on 2022-05-08 05:18

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_project_dateposted_alter_project_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='DatePosted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='Image',
            field=models.ImageField(blank=True, default='images.jpeg', upload_to='project_pics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='OpenedFor',
            field=models.CharField(max_length=2000),
        ),
    ]
